name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v1
      if: contains(github.ref, 'tags/v')
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      if: contains(github.ref, 'tags/v')
      with:
        java-version: 1.8
    - name: Get the version
      if: contains(github.ref, 'tags/v')
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Build with Gradle
      if: contains(github.ref, 'tags/v')
      env:
        GITHUB_PACKAGE_USERNAME: korosuke613
        GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GRADLE_PUBLISH_VERSION: ${{ steps.get_version.outputs.VERSION }}
      run: ./gradlew publish